name: Sync Upstream and Create PR

on:
  workflow_dispatch: # 수동으로도 실행 가능하게 설정

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "minchodang"
          git config user.email "minsu910725@gmail.com"

      - name: Fetch Upstream
        run: |
          git remote add upstream https://github.com/kode-krew/meta-test-be.git
          git fetch upstream
          git fetch origin

      - name: Check for Changes
        id: changes
        run: |
          git diff --exit-code origin/main upstream/main -- . ':(exclude).github/workflows/sync-upstream.yml' || echo "changes=true" >> $GITHUB_OUTPUT
          if [ ! -f $GITHUB_OUTPUT ]; then
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Branch and Rebase Changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          BRANCH_NAME=sync-upstream-$(date +%Y%m%d%H%M%S)
          git checkout -b $BRANCH_NAME origin/main
          git rebase upstream/main
          git push origin $BRANCH_NAME --force-with-lease
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title": "Sync with upstream",
              "body": "This PR syncs the fork with upstream repository",
              "head": "'"${{ env.BRANCH_NAME }}"'",
              "base": "main"
            }'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
