name: Sync Upstream and Create PR

on:
  schedule:
    - cron: '*/1 * * * *' # 매 분마다 실행
  workflow_dispatch: # 수동으로도 실행 가능하게 설정

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "minchodang"
          git config user.email "minsu910725@gmail.com"

      - name: Fetch Upstream
        run: |
          git remote add upstream https://github.com/kode-krew/meta-test-be.git
          git fetch upstream

      - name: Check for Changes
        id: changes
        run: |
          git diff --exit-code origin/main upstream/main -- . ':(exclude).github/workflows/sync-upstream.yml' || echo "changes=true" >> $GITHUB_OUTPUT
          if [ ! -f $GITHUB_OUTPUT ]; then
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Branch and Push
        if: steps.changes.outputs.changes == 'true'
        run: |
          git checkout -b sync-upstream-$(date +%Y%m%d%H%M%S)
          git merge upstream/main --no-edit || true
          git push origin sync-upstream-$(date +%Y%m%d%H%M%S)

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        run: |
          gh pr create --title 'Sync with upstream' --body 'This PR syncs the fork with upstream repository' --base main --head sync-upstream-$(date +%Y%m%d%H%M%S)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
